error once updated to newer sbt: 'KoanSuite.scala:52: too many arguments for method runTest: (testName: String, args: org.scalatest.Args)org.scalatest.Status'